# Name of your site (displayed in the header)
name: Google Assistant

# Short bio or description 
description: A repository of commands for google assistant.

# permalink structure
permalink: /:title

# baseurl for resource linking
baseurl: "http://shajanjp.github.io/google-assistant"